server:
  port: 1234
  error:
    include-message: always

spring:
  servlet:
  datasource:
    url: jdbc:postgresql://localhost:5432/demospringboot
    username: postgres
    password: 123456
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true


